from datetime import date
from html import escape

from owi_api.analytics.volunteer import VolunteerSummary

# Print-optimized standalone HTML — the browser's Save-as-PDF gives a clean A4 report.
# A later hardening step can render this same markup server-side for pixel-stable PDF.
_STYLE = """
  * { box-sizing: border-box; margin: 0; }
  body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
         color: #101828; padding: 40px; max-width: 800px; margin: 0 auto; }
  header { display: flex; align-items: center; gap: 14px; border-bottom: 2px solid #15803d;
           padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 1.3rem; }
  .sub { color: #667085; font-size: 0.9rem; margin-top: 2px; }
  .tiles { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }
  .tile { border: 1px solid #e9ebef; border-radius: 10px; padding: 16px; }
  .tile .v { font-size: 1.6rem; font-weight: 680; }
  .tile .l { color: #667085; font-size: 0.8rem; }
  h2 { font-size: 1rem; margin: 24px 0 10px; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e9ebef; }
  th { color: #667085; font-size: 0.75rem; text-transform: uppercase; }
  .note { color: #667085; font-size: 0.8rem; margin-top: 24px; border-top: 1px solid #e9ebef;
          padding-top: 12px; }
  @media print { body { padding: 0; } @page { margin: 18mm; } }
"""


def _tile(value: str, label: str) -> str:
    return (
        f'<div class="tile"><div class="v">{value}</div><div class="l">{escape(label)}</div></div>'
    )


def render_grant_report(
    org_name: str,
    start: date,
    end: date,
    summary: VolunteerSummary,
) -> str:
    materials = (
        "".join(
            f"<tr><td>{escape(m)}</td><td>{kg:g} kg</td></tr>"
            for m, kg in sorted(summary.kg_by_material.items(), key=lambda kv: -kv[1])
        )
        or '<tr><td colspan="2">No materials recorded</td></tr>'
    )

    trend = (
        "".join(
            f"<tr><td>{p.month}</td><td>{p.events}</td>"
            f"<td>{p.hours:g}</td><td>{p.kg:g} kg</td></tr>"
            for p in summary.monthly
        )
        or '<tr><td colspan="4">No events in range</td></tr>'
    )

    period = f"{start.isoformat()} to {end.isoformat()} · generated by OpenWaste Intelligence"
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>{escape(org_name)} — Impact Report</title><style>{_STYLE}</style></head><body>
<header>
  <div>
    <h1>{escape(org_name)} — Community Impact Report</h1>
    <div class="sub">{period}</div>
  </div>
</header>

<div class="tiles">
  {_tile(str(summary.events), "Events held")}
  {_tile(str(summary.participants), "Participants")}
  {_tile(f"{summary.hours:g}", "Volunteer hours")}
  {_tile(f"{summary.kg_total:g} kg", "Waste collected")}
</div>

<h2>Material collected</h2>
<table><thead><tr><th>Material</th><th>Weight</th></tr></thead><tbody>{materials}</tbody></table>

<h2>Activity by month</h2>
<table><thead><tr><th>Month</th><th>Events</th><th>Hours</th><th>Collected</th></tr></thead>
<tbody>{trend}</tbody></table>

<p class="note">Every figure is aggregated directly from recorded volunteer events.
Waste composition and carbon-impact sections join this report once the classification
model is live. Participation is counted in aggregate; no personal data is included.</p>
</body></html>"""
